# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20181204_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
