# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
