# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, default='img/star.png', null=True, upload_to='img'),
        ),
    ]
