# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
    ]
