# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0003_auto_20181115_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
