# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0004_remove_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 18, 30, 26, 729236)),
        ),
    ]
