# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0004_remove_comment_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
