# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0005_auto_20181115_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
