# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pobalStudio', '0008_ticket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='ticket_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
