# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pobalStudio', '0009_ticket_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=6),
        ),
    ]
